server:
  port: 8083

spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:consultingops_billing}
    username: ${DB_USER:consultingops}
    password: ${DB_PASSWORD:consultingops}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

clients:
  timesheet-service:
    url: ${TIMESHEET_SERVICE_URL:http://localhost:8082}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  security:
    jwt-secret: ${JWT_SECRET:0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF}
    internal-api-key: ${INTERNAL_API_KEY:consultingops-internal-key}

logging:
  level:
    com.consultingops.billingservice: INFO
